"""Public contract models for Compass Builder."""

from .models import (
    ContractValidationError,
    canonical_json,
    normalize_contract,
    run_binding_digest,
    validate_benchmark_aggregate,
    validate_benchmark_aggregate_receipts,
    validate_benchmark_pair,
    validate_benchmark_receipt,
    validate_benchmark_workloads,
    validate_contract,
    validate_host_capabilities,
    validate_host_capabilities_at,
    validate_run_spec,
    validate_run_bindings,
    validate_run_structure_bindings,
    validate_run_state_transition,
    validate_run_state,
    validate_wave_plan,
    validate_worker_receipt,
)
from .lease import LeaseError, LeaseHandle, acquire_lease, inspect_lease, release_lease
from .cleanup import CleanupError, cleanup_run
from .benchmark import ComparisonError, compare, validate_event_ledger
from .benchmark_runner import BenchmarkRunnerError, run_benchmark
from .controller import ControllerError, ControllerResult, execute_run
from .integrator import IntegrationError, IntegrationResult, integrate_verified_branch
from .state import (
    RepositoryIdentity, StateError, StateStore, build_execution_bundle,
    load_run_bundle, load_run_inputs, resolve_repository, validate_execution_bundle,
)
from .verifier import VerificationError, VerifiedWorker, verify_worker

__all__ = [
    "ContractValidationError",
    "canonical_json",
    "normalize_contract",
    "run_binding_digest",
    "validate_contract",
    "validate_run_spec",
    "validate_run_bindings",
    "validate_run_structure_bindings",
    "validate_run_state_transition",
    "validate_wave_plan",
    "validate_run_state",
    "validate_host_capabilities",
    "validate_host_capabilities_at",
    "validate_worker_receipt",
    "validate_benchmark_receipt",
    "validate_benchmark_workloads",
    "validate_benchmark_aggregate",
    "validate_benchmark_aggregate_receipts",
    "validate_benchmark_pair",
    "LeaseError",
    "LeaseHandle",
    "acquire_lease",
    "inspect_lease",
    "release_lease",
    "CleanupError",
    "cleanup_run",
    "ComparisonError",
    "compare",
    "validate_event_ledger",
    "BenchmarkRunnerError",
    "run_benchmark",
    "ControllerError",
    "ControllerResult",
    "execute_run",
    "IntegrationError",
    "IntegrationResult",
    "integrate_verified_branch",
    "VerificationError",
    "VerifiedWorker",
    "verify_worker",
    "RepositoryIdentity",
    "StateError",
    "StateStore",
    "build_execution_bundle",
    "load_run_bundle",
    "load_run_inputs",
    "resolve_repository",
    "validate_execution_bundle",
]
